"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const fs_1 = __importDefault(require("fs"));
const path_1 = __importDefault(require("path"));
const main = async () => {
    const basePath = path_1.default.resolve(__dirname + "/../../prompts/");
    const ret = {};
    fs_1.default.readdirSync(basePath).map((file) => {
        const key = file.split(".")[0];
        const content = fs_1.default.readFileSync(path_1.default.resolve(basePath) + "/" + file, "utf-8");
        ret[key] = content;
    });
    const code = ["// This file is auto-generated by src/tools/prompt.ts and Do not be edited manually.", `export const prompts = ${JSON.stringify(ret)};`].join("\n");
    fs_1.default.writeFileSync(path_1.default.resolve(__dirname + "/../../src/agents/prompts_data.ts"), code, "utf8");
    // console.log(hoge);
};
main();
