import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const main = async () => {
  const basePath = path.resolve(__dirname, "../../prompts/");
  const ret: Record<string, string> = {};
  fs.readdirSync(basePath).map((file) => {
    const key = file.split(".")[0];
    const content = fs.readFileSync(path.resolve(basePath, file), "utf-8");
    ret[key] = content;
  });
  const code = ["// This file is auto-generated by src/tools/prompt.ts and Do not be edited manually.", `export const prompts = ${JSON.stringify(ret)};`].join(
    "\n",
  );
  fs.writeFileSync(path.resolve(__dirname, "../../src/agents/prompts_data.ts"), code, "utf8");

  // console.log(hoge);
};

main();
